### ISSUE TITLE
How to play a playlist or a favorite

### ISSUE THREAD

**Issue by dgmltn** [svrooij/sonos2mqtt#100]
How's the best way to play a playlist or a favorite (with sonos2mqtt)? Is it setAVTransportURI? But then how's the best way to list URI's of favorites/playlists?

Thanks!

**Comment by svrooij** [comment]
You can only play streams with `SetAVTransportURI` so that would work for radio stations (or Spotify artist radio). All other stuff has to be added to a queue.

The above issue was already in my head, but I'm not sure about the best solution. Looking for input.

That would give you an option to retrieve the Favorites or the queue. Then you can play those.

**Comment by dgmltn** [comment]
But once you've "GetFavoriteRadioStations" or (how do you enumerate Sonos playlists?), can you give an example of how to replace the queue with one of the playlists you've found?

**Comment by svrooij** [comment]
The documentation of this library wasn't up-to-par. I've made some big improvements to it, see #102 

And the resulting documentation on https://svrooij.github.io/sonos2mqtt/
Your question should be answered [here](https://svrooij.github.io/sonos2mqtt/control/playback.html)

**Comment by dgmltn** [comment]
Great update, thanks!
