### ISSUE TITLE
Group Control: Publishing and Playbackinfo

### ISSUE THREAD

**Issue by 87insane** [svrooij/sonos2mqtt#110]
Hello Stephan,

I'm trying to build a player for FHEM.
I came across the topic of groups.

Whenever a group consists of several players, there is a master. The problem is that the slaves no longer receive status updates and always think they are still playing music. You only get status updates from the slaves within a group if you e.g. the volume changes. But even then "PLAYING" is also broadcast in the payload. Even if no more music is played.
If the slave leaves the group, it is immediately correct again.

It would be good if slaves in a group would get the information from the master.

Attached a picture. In this you can clearly see what I mean. (I hope)
This is a graphical representation of payload.

Sorry for my english!
![fhem_group_control](https://user-images.githubusercontent.com/47853624/86145912-d3200180-baf7-11ea-846f-077b8c1c0d95.jpg)

**Comment by svrooij** [comment]
Hi @87insane this is not a new issue, see #62 

I don’t really have a solution for this issue, any good ideas will be accepted.
The status is just returned from the speaker, no modification on it. Actually a single child player is “playing” the stream of the main speaker (called coordinator).

Maybe you can display some other status on the player if the `coordinatorUuid` is different then the `uuid`, in the [player status](https://svrooij.github.io/sonos2mqtt/topics.html#player-status). Because if it has a coordinator UUID that isn’t itself, it is for sure grouped and not playing by itself.

**Comment by 87insane** [comment]
Goedemorgen Stephan,

I am currently comparing "name" and "groupName". If name eq groupName, then NO group. If not then it's a group. The first word in the group name is always the master. e.g. Living room + 2 = group and living room is the master.

Is there such a comparison in your module? If so, one could provide the slaves / children within a group with a copy of the master data.

The playback status would suffice for me. But there may be people who want more, e.g. Track etc.

Of course, I can also convert the player and just refer to the master / coordinator. I use the group function very often and would like it to be "better". Is the idea above an option?

Greetings,
Kai

**Comment by svrooij** [comment]
The used [sonos library](https://svrooij.github.io/node-sonos-ts/) knows if a player is a member player or a coordinator, so that part is easy.

But the events are a different thing, they are separated per [service](http://svrooij.io/node-sonos-ts/sonos-device/services/services.html) per speaker, then at [speaker level](https://github.com/svrooij/node-sonos-ts/blob/master/src/sonos-device.ts#L516-L597) the events from the **RenderingControlService** and the **AVTransportService** are also emitted as events for the speaker.

If you want the speaker to also emit events based on events from the coordinator, each speaker in a group would have to subscribe to the events from the coordinator once joined in the group. And those events would be duplicates of the events of the coordinator. The coordinator data is available at `sonos/player_uuid` if you would that the `coordinatorUuid` from the response of the player, not sure how that works in FHEM.

1. Listen for all players, subscribe to: `sonos/+`.
2. For each player you display the regular status, unless the `coordinatorUuid != uuid`.
3. Then you take the data from `sonos/coordinatorUuid`.

Of even better 

1. Listen for all players, subscribe to: `sonos/+`.
2. Use the speaker name and volume from the player status and the playback data from
  `sonos/coordinatorUuid` where you fill in the correct uuid that you got from the device data.
  Also for single players this is correct because the coordinatorUuid will be itself.

This is a pretty substantial change for which I have no time for at the moment. As [stated](https://github.com/sponsors/svrooij) on my sponsoring profile, I would like to spend more time on Home Automation stuff, but time is somewhat limited right now. So if you want to give it a go, feel free to submit a PR :wink:

I can imagine that it would also be possible to **clear** the track data, if it receives a [coordinator update](https://github.com/svrooij/sonos2mqtt/blob/master/src/sonos-to-mqtt.ts#L125-L130), that would be a much smaller change.

**Comment by viimD** [comment]
I'm also struggling with this issue. I figured out how to start for example Radio 3FM on my speakers. I do this by sending this message to the coördinator speaker 'wittekast keuken' (sonos/wittekast-keuken/control):
{    "command": "setavtransporturi",
    "input": "radio:s6707?sid=254&flags=32"}

This works fine, both the speaker 'wittekast keuken' and 'keuken' (which are in the same group), play 3FM. However, when I want to increase the volume of both speakers it does not work. I send the following message also to the coördinator speaker 'wittekast keuken' (sonos/wittekast-keuken/control):
{    "command": "volumeup",
    "input": 5}

Now only the volume of the 'wittekast keuken' is raised by 5. The volume of the member 'keuken' remains unchanged. Do I miss something somewhere?

**Comment by svrooij** [comment]
@viimD you issue is unrelated to the above. Volume is per speaker, but [some](https://svrooij.io/node-sonos-ts/sonos-device/methods.html#shortcuts) commands are automatically redirected to the group coordinator.

**Comment by svrooij** [comment]
@87insane you had to wait for this one quite long. I've now added 2 extra transport states, `GROUP_PLAYING` and `GROUP_STOPPED` that are emitted for all players in the group. So if the player has one of these you should hide the track info and disable the controls. But you can still display whether or not it's playing music at the moment.
