### ISSUE TITLE
Does this work with Spotify Free on Sonos?

### ISSUE THREAD

**Issue by probonopd** [svrooij/sonos2mqtt#117]
Does this work with Spotify Free on Sonos? (No paid Spotify account)

**Comment by svrooij** [comment]
This library just controls your speakers like the controller app would do.But .....

- You cannot trigger the login to Spotify (yet ❤️ )
- You cannot search for spotify music (yet ❤️ )

You can however just send a command to start a playlist (as described [here](https://svrooij.io/sonos2mqtt/control/playback.html))

And because I don't like ads in between music, I've got a paid account for spotify, so support for free spotify is untested (but should work). Closing this issue for now, please re-open if you cannot get it to work.

---

❤️ Searching spotify (and triggering the login), is something I'm currently working on but this won't be released until I've got at least 20 [github sponsors](https://github.com/sponsors/svrooij)

**Comment by probonopd** [comment]
Thank you.
