### ISSUE TITLE
autostart

### ISSUE THREAD

**Issue by MBj1703** [svrooij/sonos2mqtt#123]
Hi,

is there ar way to autostart sonos2mqtt on system boot?

**Comment by svrooij** [comment]
I run sonos2mqtt in [docker](https://svrooij.io/sonos2mqtt/getting-started.html#run-sonos2mqtt-in-docker), it is started at systemboot because I told it to (started with `restart`: `unless-stopped`).

If you're running the app without docker, you could check out [pm2](https://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/). But since I use docker for everything, running the app without docker is not something I can support.

**Comment by svrooij** [comment]
If you need further information about this you can re-open the issue.

**Comment by rliegmann** [comment]
Hello everybody,

I would like to reopen and expand this Issues.
Is there a way to start the Docker Container if there is currently no Sonos device in the network? The reason for this is that the Sonos devices are not always on power. The container always stops after two attempts.

Thanks :-)
