### ISSUE TITLE
Switching Radio-Favorites results in mutliple STOPPED transportSate messages 

### ISSUE THREAD

**Issue by 0815nils** [svrooij/sonos2mqtt#125]
Hi Stephan,

first of all: thank you for your implementation. Installation and start working with it was really easy :)

My Problem:
Switching my Radio-Favorites (TuneIn) with the sonos mac app results in mutliple STOPPED transportSate messages (at least 2) and after that transmission and playing starts. I am receiving the messages with my node red mqtt node...

Can you or anyone else confirm this behaviour or do you need more details?

Cheers 
Nils

**Comment by svrooij** [comment]
The sonos speaker actually sends a stopped event (it stops playing the current stream) when switching to some other stream. This also happens if you switch from radio back to the queue, or the other way around.

Nothing we can do about, you could try to fix something with the **delay** node.

Since I cannot do anything about this (it already delays sending the full status message for 400 milliseconds), I'm closing this. If you got an idea on how this could be fixed, please re-open this issue.
