### ISSUE TITLE
Messages on sonos/status/+ are not retained

### ISSUE THREAD

**Issue by peti69** [svrooij/sonos2mqtt#158]
I noticed that information posted by sonos2mqtt to the topics sonos/status/+ is not retained. Is there a reason for that since messages on sonos/<uuid> have the retain flag set?

Retained messages have the great advantage that a new topic subscriber immediately has the latest status.

Any feedback is welcome.

**Comment by svrooij** [comment]
The topics your referring to is the artifact of how it all started. If I’m correct all the data in those topics is also in the combined status message. Why would you want to use those separated topic? If there is a good reason we can just enable retaining them, as long as it’s configurable.

The reason to not retain them is because in my opinion an app should be able to clean all topics if the user wants that. By only retaining the combined messages the amount of messages to clear would be small.

**Comment by peti69** [comment]
Thanks for your answer. I will make use of combined status message which is retained.
