### ISSUE TITLE
[Feature] Notification before TTS

### ISSUE THREAD

**Issue by bstaeheli** [svrooij/sonos2mqtt#167]
Dear sonos2mqtt team

We have been using mqtt2sonos for some time now in conjunction with our FHEM instance. We are super satisfied, thank you so much for your great work! In my opinion it runs much more stable than with the native FHEM implementation of SONOS. 

Only one feature I miss. You can enter a sound before the text to be spoken, enclosed in two pipes, which is played shortly before the announcement. This helps so that we and our guests are not so frightened when suddenly a voice sounds out of nowhere that the washing machine has finished its work.

Examples (copied from the [FHEM Wiki](https://wiki.fhem.de/wiki/SONOS#Set-Befehle_an_den_SONOSPLAYER))

- **|/path/to/Gong.mp3|** Attention! Attention! The washing machine has finished.
- The file can also be **|/path/to/Tada.mp3|** in the middle.
- **|/path/to/Gong.mp3|** Several files can also be embedded **|/path/to/Tada.mp3|**.

Is it possible to implement something like this?

Thank you very much for considering my request,
Boris

**Comment by svrooij** [comment]
@bstaeheli it's just me for now 😉

I think you should just send the two notifications right after each other. Since a year or so there is a notification queue.

So if you want ding, message you just send
Notification: Ding and then TTS: message. Not really sure how that works in FHEM.

And maybe if I see the time I can implement something like you suggest. That you can specify multiple notifications separated by a `|`

**Comment by svrooij** [comment]
@bstaeheli upon review of your suggestion, I think this isn't possible.

Isn't is possible to send 2 commands right after each other? something like:

```shell
sonos PlayURITemp http://url.to.bell/file.mp3 20
sonos speak 20 de-de some text
```

**Comment by bstaeheli** [comment]
@svrooij, thanks for your suggestions. 

Does your solution restart the song/stream after the "speak"? 

I tried the notifytwo and speaktwo, sometimes it works, sometimes not. Not sure why.

We're out of home for the next weeks, so i'm not able to test.

**Comment by svrooij** [comment]
@bstaeheli is your issue fixed with the provided solution? If not please re-open the issue.

In my own setup the `Notify` and `Speak` commands are really stable. Calling them once creates a notification queue and reverts afterwards. Calling them more then once in rapid succession adds songs to the queue and continues playing the current songs.

As long as the original song was "known" that is. Meaning started with the sonos app or sonos2mqtt, we cannot revert back to songs started from the spotify app or a voice assistant.
