### ISSUE TITLE
bug: SONOS2MQTT_FRIENDLYNAMES env var doesn't work

### ISSUE THREAD

**Issue by tracetechnical** [svrooij/sonos2mqtt#183]
Setting SONOS2MQTT_FRIENDLYNAMES env var  to "name" doesn't seem to set the friendlynames flag as expected.

Checked yargs docs to see if I was being daft, but it appears not.

**Comment by tracetechnical** [comment]
Also appears that the --friendlynames flag itself doesn't work, in my testing.

**Comment by svrooij** [comment]
This is the result when I set `SONOS2MQTT_FRIENDLYNAMES` to `uuid`:
![image](https://user-images.githubusercontent.com/1292510/219395019-a4451fab-56d0-4f4a-8ed4-6895a501ddbe.png)

That means the config is loaded correctly.

The `{prefix}/{player_uuid}` topic will never change, this message includes the complete status and will always use the uuid.

The `SONOS2MQTT_FRIENDLYNAMES` setting only influences the distinct topics, that you need to activate by setting the `SONOS2MQTT_DISTINCT` to `true` (or by including the `--distinct` flag.

Which will result in the following messages in the mqtt server.

set to `uuid`
![image](https://user-images.githubusercontent.com/1292510/219397460-64872f13-f968-463f-b47a-481ca03730bc.png)

Set to `name` (or skipped because it's the default).
![image](https://user-images.githubusercontent.com/1292510/219397942-4ee2a33f-fab8-41ae-b2a0-ad1728fa0e98.png)

I think this might need addition explanation in the docs, but is works like I build it, so I'm closing this issue for now. You can always re-open if you think this is incorrect.
