### ISSUE TITLE
How to start playing a Sonos Radio, might be specific issue with "VRT Radio 1"

### ISSUE THREAD

**Issue by lucsegers** [svrooij/sonos2mqtt#204]
I have following radio in my favorite list:

```json
    {
      "AlbumArtUri": "https://assets.radioplayer.org/056/0565001/600/600/l45a5apx.png",
      "Title": "Radio 1",
      "UpnpClass": "object.itemobject.item.sonos-favorite",
      "ItemId": "FV:2/9",
      "ParentId": "FV:2",
      "TrackUri": "x-sonosapi-stream:shlsTemp:5001?sid=232&flags=8232&sn=7",
      "ProtocolInfo": "x-sonosapi-stream:*:*:*"
    },
```

I am wondering how I should play this radio with the sonos2mqtt. This radio always start with a 4-5 seconds add before the stream is really playing, I'm wondering if sonos2mqtt has a problem with that.

I used

```json
{
    "command": "setavtransporturi",
    "input": "x-sonosapi-stream:shlsTemp:5001?sid=232&flags=8232&sn=7"
}
```

but that only sets the radio and it is not being played. In the recent played list on "my Sonos" it does not list "Radio 1" but it lists "Some radio station".
Something is still wrong, but I can not put my finger on it.

BTW this is "VRT Radio 1" if you want to search for it in your Sonos S2 app.

**Comment by svrooij** [comment]
Streams are still troublesome.... It's like that since like for ever.

Have you checked the docs at: https://sonos2mqtt.svrooij.io/control/playback.html ?

My suggestion is that you start the stream with the regular app, and then check the full details for the stream. You're looking for the metadata. The stream URL you provided is not supported by the Metadata helper.

And then finally you'll have to send a request like [this](https://sonos2mqtt.svrooij.io/control/playback.html#play-a-single-item-for-experts)

I guess it's this:

```json
{
  "command": "adv-command",
  "input": {
    "cmd": "AVTransportService.SetAVTransportURI",
    "val": {
      "InstanceID": 0,
      "CurrentURI": "x-sonosapi-stream:shlsTemp:5001?sid=232&flags=8232&sn=7",
      "CurrentURIMetaData": {
        "Title": "Radio 1",
        "ItemId": "FV:2/9",
        "ParentId": "FV:2",
        "ProtocolInfo": "x-sonosapi-stream:*:*:*",
        "UpnpClass": "object.itemobject.item.sonos-favorite"
      }
    }
  }
}
```

**Comment by svrooij** [comment]
@lucsegers can you validate this works?
