### ISSUE TITLE
2.0.0: MQTT connection issue

### ISSUE THREAD

**Issue by flic** [svrooij/sonos2mqtt#37]
I can't seem to get the dockerized v2.0.0 to connect to Mosquitto:

2019-12-25 10:13:35.008 <info>  mqtt reconnect
2019-12-25 10:13:35.010 <info>  mqtt closed mqtt://xxxx:yyyy@192.168.240.2

I can't see anything in the Mosquitto logs. Anybody else have any issues with this?

**Comment by svrooij** [comment]
I’ve updated the used [mqtt](https://www.npmjs.com/package/mqtt#client) version to 3.x, it seems they have a new way to specify the username and password.
Not sure if this got something to do with the docker, think it might be an issue with the app itself.

Think I might need to build a way to specify the other mqtt options instead of just the url.

Will have a got on it after Christmas 🎄 🎅 .

**Comment by svrooij** [comment]
@flic can you check what happens if you remove the username and password from the url? That should make it connect but have the password fail (log in mosquitto). Also are you sure the ip of your mqtt server is correct? Should probably be the internal docker ip of the mqtt server.

**Comment by flic** [comment]
Doesn't seem to matter.

I've tried removing user:pass from the URL (and configuring Mosquitto to allow_anonymous), tried the internal Docker IP, container name, host IP, no difference. I'm not getting any indication in the Mosquitto log that sonos2mqtt even tries to connect.

Other containers on the same host can connect.

**Comment by svrooij** [comment]
What is de version of your mosquitto server? The underlying mqtt lib switch to default 3.1.1 protocol, which can be configured to be lower, but should be supported by the current version of mosquitto.

If I got the same version of mosquitto that should make it easy to check and verify.

**Comment by flic** [comment]
I was running 1.6.7. Tried pulling eclipse-mosquitto:latest which brought me up to 1.6.8, but with the same result.

**Comment by svrooij** [comment]
I replicated the issue... Not working inside docker, but working outside docker.... going to try an other mqtt server. just for reference

**Comment by svrooij** [comment]
Tested the following situations:

|env|url/options|mqtt version|mqtt server|success|
|---|-----------|-------------|--------|-------|
|local sonos2mqtt|url|v3.0.0|mosquitto|:white_check_mark:|
|local sonos2mqtt|url|v3.0.0|emqx|:white_check_mark:|
|local sonos2mqtt|url|v2.18.1|mosquitto|:white_check_mark:|
|local sonos2mqtt|url|v2.18.1|emqx|:white_check_mark:|
|docker sonos2mqtt|url|v3.0.0|mosquitto|:x:|
|docker sonos2mqtt|url|v3.0.0|emqx|:x:|
|docker sonos2mqtt|url|v2.18.1|mosquitto|:x:|
|docker sonos2mqtt|url|v2.18.1|emqx|:x:|
|local sonos2mqtt|options|v3.0.0|mosquitto|:santa:|
|local sonos2mqtt|options|v3.0.0|emqx|:santa:|
|local sonos2mqtt|options|v2.18.1|mosquitto|:santa:|
|local sonos2mqtt|options|v2.18.1|emqx|:santa:|
|docker sonos2mqtt|options|v3.0.0|mosquitto|:santa:|
|docker sonos2mqtt|options|v3.0.0|emqx|:white_check_mark:|
|docker sonos2mqtt|options|v2.18.1|mosquitto|:santa:|
|docker sonos2mqtt|options|v2.18.1|emqx|:santa:|

:santa: == probably works, don't want to test since it's christmas.

I'll have to modify the config part so you can specify all the needed [config options](https://github.com/mqttjs/MQTT.js#mqttclientstreambuilder-options). It seems that parsing the url doesn't work quite well anymore.

**Comment by flic** [comment]
Damn, you're fast! :)

**Comment by svrooij** [comment]
:wink: https://github.com/sponsors/svrooij
