### ISSUE TITLE
Best way of grouping speakers

### ISSUE THREAD

**Issue by flic** [svrooij/sonos2mqtt#45]
This is perhaps not wholly related to sonos2mqtt, but  I hope you don't mind me asking the question since you (and probably other users of this project) seems very knowledgeable about Sonos.

I have quite a few speakers and I group them differently depending of use. In the morning the Alexa alarm triggers music on certain speakers, when I arrive home in the evening I want others and so on.

I solve this by sending a leavegroup to the speaker I'd like to be the coordinator, joingroup to the other players and then play to the coordinator. I stagger the commands by approx 500ms to not overwhelm the system. It works, sonos2mqtt does its work, but the Sonos system itself is slow, and not all that stable. Most of the time it works although it takes a fairly long time. A lot of the time one or more speaker doesn't join or join but doesn't play. (That last one is a bit weird)

Is there a better way to do this?

**Comment by svrooij** [comment]
not sure what you're trying to accomplish.
Grouping takes time, I cannot help that. On the sonos side it's one of the longest tasks (like 100/200ms).

But this bridge (and ultimately the used [library](https://github.com/svrooij/node-sonos-ts)) keeps track of the group coordinator. So a lot of [commands](https://github.com/svrooij/node-sonos-ts/blob/master/src/sonos-device.ts#L814L856) are send to the coordinator automatically.

You can also join a group by directly sending the [right command](https://github.com/svrooij/node-sonos-ts/blob/master/src/sonos-device.ts#L276L283). The current way does a lookup by name because the ID's are hard to remember

**Comment by flic** [comment]
Yes, that was pretty much what I was expecting, thanks for taking the time answering my question. I'll play around a bit using the IDs instead, see if that speeds it up some. Do you know if there's any way to speed up the process on the Sonos side? Hardwire one of the speakers perhaps or set up some sort of preset, anything like that?

**Comment by svrooij** [comment]
Just leave them grouped :wink:

The build-in alarms have an option to don't play on grouped players. you can have it re-join after the the alarm. You could make a preferred rest method, to which it returns when you aren't using the speakers. That way it doesn't matter if it takes long.

I haven't found it to be instable though. you can fire as many commands as you want.
